[package]
name = "auto-services"
version.workspace = true
edition.workspace = true

[dependencies]
service-protos = { path = "../service-protos" }
ip-service = { path = "../ip-service" }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }

[build-dependencies]