name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Checks:
    name: checks

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-protoc
      run: ./scripts/install_protoc.sh
    - name: Run tests
      run: cd auto-service; cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: Run clippy all
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run fmt
      run: cargo +nightly fmt --all -- --check --files-with-diff

  Build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install-protoc
        run: ./scripts/install_protoc.sh
      - name: Build
        run: cd auto-service; cargo build --verbose
